name: Build Signed Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Platform Files
        run: flutter create --platforms android .

      - name: Fix Android Min SDK Version
        run: |
          if [ -f android/app/build.gradle ]; then
            sed -i 's/flutter.minSdkVersion/21/g' android/app/build.gradle
          fi
          if [ -f android/app/build.gradle.kts ]; then
            sed -i 's/flutter.minSdkVersion/21/g' android/app/build.gradle.kts
          fi

      - name: Add Microphone Permission
        run: sed -i '/<application/i \    <uses-permission android:name="android.permission.RECORD_AUDIO"/>' android/app/src/main/AndroidManifest.xml

      - name: Install dependencies
        run: flutter pub get

      - name: Build Unsigned APK
        run: flutter build apk --release

      - name: Generate Production Keystore
        run: keytool -genkey -v -keystore release.jks -keyalg RSA -keysize 2048 -validity 10000 -alias tiger -storepass tiger1234 -keypass tiger1234 -dname "CN=Tiger Tasks, OU=Development, O=Tech, L=Madurai, S=Tamil Nadu, C=IN"

      - name: Sign the APK
        run: |
          BUILD_TOOLS_VERSION=$(ls $ANDROID_HOME/build-tools | sort -n | tail -1)
          $ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION/apksigner sign --ks release.jks --ks-pass pass:tiger1234 --ks-key-alias tiger build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Signed Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tiger-tasks-signed-app
          path: build/app/outputs/flutter-apk/app-release.apk
